In [ ]:
#training phase
#lookup table (dictionary or other)
# we search the whole dataset and create lookup table that contains all probs

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('play_tennis_naivebayes.csv')
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [ ]:
df.drop(columns=['day'],inplace=True)

In [ ]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
label=dict(df['play'].value_counts())

In [ ]:
print(label)

{'Yes': 9, 'No': 5}

In [ ]:
pd.crosstab(df['outlook'],df['play'])
#now can calc directly

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
pd.crosstab(df['temp'],df['play'])
#now can calc directly

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pd.crosstab(df['humidity'],df['play'])
#now can calc directly

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
pd.crosstab(df['wind'],df['play'])
#now can calc directly

play    No  Yes
wind
Strong   3    3
Weak     2    6